### ISSUE TITLE
UI 컬러

### ISSUE THREAD

**Issue by YEBEENPARK** [ProjectInTheClass/moongaemoongae#3]
Blue 계열 Color palette 고르기

**Comment by aa9390** [comment]
![image](https://user-images.githubusercontent.com/24476756/42856463-5c7b4ad4-8a80-11e8-9301-bb81a855fe24.png)

**Comment by YEBEENPARK** [comment]
![image](https://user-images.githubusercontent.com/41043934/42856493-78d3c59e-8a80-11e8-90c1-f7b89cadd822.png)

**Comment by YEBEENPARK** [comment]
![image](https://user-images.githubusercontent.com/41043934/42856498-7e69f51e-8a80-11e8-8c45-8a9c778ddf92.png)

**Comment by YEBEENPARK** [comment]
![image](https://user-images.githubusercontent.com/41043934/42856586-d264d60c-8a80-11e8-8c2a-2934310d4ab2.png)

**Comment by YEBEENPARK** [comment]
![image](https://user-images.githubusercontent.com/41043934/42856596-de9c7b6e-8a80-11e8-97fe-4b6fa6a40753.png)

**Comment by aa9390** [comment]
![image](https://user-images.githubusercontent.com/24476756/42856617-f12389b2-8a80-11e8-85bc-58a3c5f85c3f.png)

**Comment by Jae-eun** [comment]
<img width="408" alt="2018-07-18 1 12 33" src="https://user-images.githubusercontent.com/12438429/42859000-61c891d4-8a8c-11e8-8e30-4bd52498e70a.png">

**Comment by Jae-eun** [comment]
<img width="529" alt="2018-07-18 1 16 17" src="https://user-images.githubusercontent.com/12438429/42859050-c5e3e18c-8a8c-11e8-9ecf-d5e0ba2fc8ff.png">

**Comment by Jae-eun** [comment]
<img width="508" alt="2018-07-18 1 19 16" src="https://user-images.githubusercontent.com/12438429/42859135-39c4bde2-8a8d-11e8-9e29-eeff1aa6cf5f.png">

**Comment by Jae-eun** [comment]
<img width="528" alt="2018-07-18 1 21 33" src="https://user-images.githubusercontent.com/12438429/42859202-82a73b48-8a8d-11e8-9b79-4fbde7d30b99.png">

**Comment by aa9390** [comment]
![image](https://user-images.githubusercontent.com/24476756/43434890-99e7a68c-94b8-11e8-8095-a22c7e50ddfd.png)

**Comment by aa9390** [comment]
![image](https://user-images.githubusercontent.com/24476756/43434902-a25bb47a-94b8-11e8-847c-4eab41bfa20d.png)
![image](https://user-images.githubusercontent.com/24476756/43434906-a62b1942-94b8-11e8-9767-1c2bcc8a026a.png)
![image](https://user-images.githubusercontent.com/24476756/43434909-a8b9a584-94b8-11e8-9aa8-933c2b71e86f.png)
![image](https://user-images.githubusercontent.com/24476756/43434915-aba27906-94b8-11e8-8788-4c36fa7aaec9.png)
